openapi: 3.0.0
info:
  title: Project Management API
  version: 1.0.0
paths:
  /projects:
    get:
      summary: List all projects
      responses:
        '200':
          description: A list of projects
    post:
      summary: Create a new project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectInput'
      responses:
        '201':
          description: Project created
  /projects/{id}:
    get:
      summary: Get project details
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Project details
    put:
      summary: Rename a project
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Project renamed
    delete:
      summary: Delete a project
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Project deleted
components:
  schemas:
    ProjectInput:
      type: object
      required:
        - name
        - type
      properties:
        name:
          type: string
        type:
          type: string
          enum: [prose, poetry, drama]
        details:
          type: string
